### ISSUE TITLE
Ground Clearance

### ISSUE THREAD

**Issue by Raidklw** [parkingdata/spec#9]
Both the Qualification and the Maximum Dimensions classes include maximum height dimensions, but do not include ground clearance requirements.

Use case: An parking deck or lot has speed bumps or rough terrain. As a result, the operator wants to prohibit vehicles with low ground clearance.

Suggested resolution:
Add groundClearance as an optional attribute to the IdentifiedArea/MaximumDimensions class. Create a GroundClearanceCharateristic class in the Eligibility package and create groundClearanceCharacteristic as an attribute in the Eligibility/Qualification class

**Comment by JHB9876** [comment]
Suggestion noted.  Added to ISO WD Comments.  JHB notes - MaximumDimension class exists in VehicularAccess and Space, not IdentifiedArea.
